# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 597a00df717fbdbdac4756dd6636fa955dd198024d5f68b7eb76dbc922d19e1825b225f94bc2dc6485daff84890727c49ea3d13405a78385e6f5c9d6814d563e

test:
  secret_key_base: 76303bb2bca51e505eb4a1d7708223bd897dde5505d20da7f864f3cfd039e49c3c74f769c44347915cc06a6ff8ba4114e9eff37001de83c9469048a71d220bdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
